apiVersion: v1
kind: Service
metadata:
  name: bittest-headless-service
spec:
  clusterIP: None  # Isso define o serviço como headless
  selector:
    app: bittest-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000